[package]
name = "visio-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
visio-core = { path = "../visio-core" }
visio-video = { path = "../visio-video" }
uniffi = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"
libwebrtc = "0.3.26"
livekit = { workspace = true, features = ["rustls-tls-webpki-roots"] }

[target.'cfg(target_os = "ios")'.dependencies]
livekit = { workspace = true, features = ["rustls-tls-webpki-roots"] }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
webrtc-sys-build = "0.3"

[features]
default = []
cli = ["uniffi/cli"]

[[bin]]
name = "uniffi-bindgen"
required-features = ["cli"]
